https://www.linkedin.com/badges/profile/create?vanityname=dukebode&preferredlocale=zh_CN&trk=public_profile-settings_badge

<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>

主框架 280

<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="zh_CN" data-type="horizontal" data-theme="light" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="zh_CN" data-type="horizontal" data-theme="dark" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

主框架 330

<div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="zh_CN" data-type="horizontal" data-theme="light" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

<div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="zh_CN" data-type="horizontal" data-theme="dark" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

侧边栏 250

<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="zh_CN" data-type="vertical" data-theme="light" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

<div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="zh_CN" data-type="vertical" data-theme="dark" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

侧边栏 300

<div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="zh_CN" data-type="vertical" data-theme="light" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>

<div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="zh_CN" data-type="vertical" data-theme="dark" data-vanity="dukebode"><a class="LI-simple-link" href='https://cn.linkedin.com/in/dukebode?trk=profile-badge'>博德蝈蝈</a></div>